#!/bin/sh

file=f/F.php

cat > $file << EOF
<?php

namespace f;

class F
{
	use Fallback;

	private static \$instance;

	static function getInstance()
	{
		if(empty(self::\$instance))
		{
			self::\$instance = new F;
		}
		return self::\$instance;
	}
	
EOF

for path in f/*; do
	bname=$(basename "$path")
	fname="${bname%.*}"

	if [ "$fname" = F ] || [ "$fname" = Fallback ]; then
		continue
	fi

	sed -e "/^return/ s/return function\(.*\){/\n\tpublic function $fname\1{/" \
		-e "s/^};/}/" \
		-ne "/^[^<]/ s/.*/\t&/p" < $path >> $file

done


echo '}' >> $file
